### ISSUE TITLE
Is there any pretrained models?

### ISSUE THREAD

**Issue by Amaris168** [batsa003/videogan#2]
hello! Is there any pretrained models in your code? The video dataset is too large and I can't train a model from the very beginning. Thank you!

**Comment by batsa003** [comment]
Here are my pre-trained generators and discriminators:
https://drive.google.com/drive/folders/1AuKmC0o6umf6MWUaZPPjA9RAbNJ4oMrV?usp=sharing
I hope you find them useful.

**Comment by Amaris168** [comment]
Oh, it’s really helpful. Thanks a lot!
